name: Bug Report
description: Report a bug / crash
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        To help us help you, please provide as much information as you can, this helps us with debugging and reproducing the issue.
  - type: input
    id: mobfarming-version
    attributes:
      label: Efficient Mob Farming Version
      description: |
        You can find the version of the mod in the mods file name or in-game in the mods button on the main menu.
      placeholder: 0.1.0
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      placeholder: 1.21.0
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: (Neo)Forge Version
      description: |
        You can get this from the main menu screen in the bottom left corner of the screen.
      placeholder: 40.1.20
    validations:
      required: false
  - type: input
    id: modpack
    attributes:
      label: Modpack & Version
      description: |
        If you are running a Modpack, please provide the name and version of the pack.
      placeholder: Example Modpack 1.0
    validations:
      required: false
  - type: dropdown
    id: optifine
    validations:
      required: false
    attributes:
      label: Do you have optifine or Rubidium installed?
      description: |
        If you have a different rendering mod installed, please add to in the extra info box at the end.
      multiple: false
      options:
        - 'Yes'
        - 'No'
        - 'I have other rendering based mods installed'
  - type: input
    id: bugdesc
    attributes:
      label: Describe the issue
      description: |
        A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Tell us how we can reproduce the issue
      placeholder: |
        1. Open Minecraft...
        2. Click block...
        3. Everything goes black...
    validations:
      required: true
  - type: input
    id: expectedBehaviour
    attributes:
      label: Expected behaviour
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: "Link(s) to any log files that you can provide, typically, /logs/debug.log and /logs/latest.log"
      placeholder: |
        https://pastelog.us/
        https://pste.ch/ihaveaproble
        https://pastebin.com/
        https://paste.feed-the-beast.com/
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the problem here
    validations:
      required: false